dictionaries = ["en_us"]
words = [
	"changelogithub",
	"bumpp",
	"bexport",
	"billboardgui",
	"bruh",
	"canvasgroup",
	"cjs",
	"codestral",
	"ecs",
	"filenaming",
	"flamework",
	"gsub",
	"hedgefund",
	"hexflame",
	"hoverable",
	"ianitor",
	"iif",
	"imagebutton",
	"imagelabel",
	"jsr",
	"keypoint",
	"knip",
	"leaderboard",
	"matchers",
	"mcp",
	"multimodal",
	"oxfmt",
	"oxfmtrc",
	"oxlint",
	"oxlintrc",
	"reroll",
	"sandboxed",
	"screengui",
	"scriptability",
	"scrollingframe",
	"serde",
	"setmetatable",
	"shfmt",
	"spritesheet",
	"sse",
	"taze",
	"textbutton",
	"textlabel",
	"tonumber",
	"tsdown",
	"tsgo",
	"uiaspectratioconstraint",
	"uicorner",
	"uiflexitem",
	"uigradient",
	"uigridlayout",
	"uilistlayout",
	"uipadding",
	"uiscale",
	"uisizeconstraint",
	"uistroke",
	"unobserve",
	"viewportframe",
	"vscode",
	"vtsls",
	"zprofile",
	"zshenv",
	"stryker",
]
ignore_paths = [
	"scripts/generate-default-properties.ts",
]
