import { describe } from "vitest";

import rule from "$oxc-rules/general/no-trivial-assertions";

import { js, ts } from "./rule-testers";

describe("no-trivial-assertions", () => {
	js.run("no-trivial-assertions", rule, {
		invalid: [
			{
				code: "expect(true).toBe(true);",
				errors: [{ messageId: "issue" }],
				documentation: { id: "fail", title: "Constant always-true equality" },
			},
			{ code: "expect(1).toBe(1);", errors: [{ messageId: "issue" }] },
			{ code: "expect('a').toEqual('a');", errors: [{ messageId: "issue" }] },
			{ code: "expect(false).toBeFalsy();", errors: [{ messageId: "issue" }] },
			{ code: "expect(true).toBeTruthy();", errors: [{ messageId: "issue" }] },
			{ code: "expect(undefined).toBeUndefined();", errors: [{ messageId: "issue" }] },
			{ code: "expect(null).toBeNull();", errors: [{ messageId: "issue" }] },
			{ code: "expect(0).toBeFalsy();", errors: [{ messageId: "issue" }] },
			{ code: "expect('').toBeFalsy();", errors: [{ messageId: "issue" }] },
			{ code: "expect(!false).toBe(true);", errors: [{ messageId: "issue" }] },
			{ code: "expect(-1).toBe(-1);", errors: [{ messageId: "issue" }] },
			{ code: "expect(+1).toBe(1);", errors: [{ messageId: "issue" }] },
			{ code: "expect(void 0).toBeUndefined();", errors: [{ messageId: "issue" }] },
			{ code: "expect(typeof 1).toBe('number');", errors: [{ messageId: "issue" }] },
			{ code: "expect(/x/).toBe(/x/);", errors: [{ messageId: "freshIdentity" }] },
			{ code: "expect(() => {}).toBeTruthy();", errors: [{ messageId: "freshPredicate" }] },
			{ code: "expect(function () {}).toBeTruthy();", errors: [{ messageId: "freshPredicate" }] },
			{ code: "expect(class X {}).toBeTruthy();", errors: [{ messageId: "freshPredicate" }] },
			{ code: "expect({}).toBe({});", errors: [{ messageId: "freshIdentity" }] },
			{ code: "expect([]).toBe([]);", errors: [{ messageId: "freshIdentity" }] },
			{ code: "expect(new Error()).toBe(new Error());", errors: [{ messageId: "freshIdentity" }] },
			{ code: "expect({}).toBeTruthy();", errors: [{ messageId: "freshPredicate" }] },
			{ code: "expect(value).not.toBe({});", errors: [{ messageId: "freshIdentity" }] },
			{ code: "assert.strictEqual(1, 1);", errors: [{ messageId: "issue" }] },
			{ code: "assert.equal(true, true);", errors: [{ messageId: "issue" }] },
			{ code: "assert.notStrictEqual(1, 2);", errors: [{ messageId: "issue" }] },
			{ code: "assert.ok(true);", errors: [{ messageId: "issue" }] },
			{ code: "assert.notOk(false);", errors: [{ messageId: "issue" }] },
			{ code: "assert.strictEqual({}, {});", errors: [{ messageId: "freshIdentity" }] },
			{ code: "assert.deepEqual(1, 1);", errors: [{ messageId: "issue" }] },
			{ code: "assert.notEqual(1, 2);", errors: [{ messageId: "issue" }] },
			{
				code: "const flag = true;\nexpect(flag).toBe(true);",
				errors: [{ messageId: "issue" }],
			},
			{
				code: "expect(1n).toBe(1n);",
				errors: [{ messageId: "issue" }],
			},
			{ code: "expect(true).toBeDefined();", errors: [{ messageId: "issue" }] },
			{ code: "expect(false).toBeDefined();", errors: [{ messageId: "issue" }] },
			{ code: "expect(0n).toBeFalsy();", errors: [{ messageId: "issue" }] },
			{ code: "expect({}).not.toBeNull();", errors: [{ messageId: "freshPredicate" }] },
			{ code: "expect({}).not.toBeUndefined();", errors: [{ messageId: "freshPredicate" }] },
			{ code: "expect({}).not.toBeFalsy();", errors: [{ messageId: "freshPredicate" }] },
			{ code: "expect([]).toBeDefined();", errors: [{ messageId: "freshPredicate" }] },
			{ code: "expect(/x/).toBeTruthy();", errors: [{ messageId: "freshPredicate" }] },
			{ code: "expect(value).toBe([]);", errors: [{ messageId: "freshIdentity" }] },
			{ code: "assert.notDeepStrictEqual(1, 2);", errors: [{ messageId: "issue" }] },
			{ code: "assert.notDeepEqual(1, 2);", errors: [{ messageId: "issue" }] },
			{ code: "assert.deepStrictEqual(1, 1);", errors: [{ messageId: "issue" }] },
			{ code: "assert.notStrictEqual({}, 1);", errors: [{ messageId: "freshIdentity" }] },
			{ code: "expect(null).toBe(null);", errors: [{ messageId: "issue" }] },
		],
		valid: [
			{
				code: "expect(result).toBe(true);",
				documentation: { id: "pass", title: "Non-constant assertion" },
			},
			"expect(result).toBe(expected);",
			"expect(value).toEqual({ a: 1 });",
			"expect(value).toStrictEqual({ a: 1 });",
			"expect(items).toHaveLength(2);",
			"expect(value).toBeTruthy();",
			"expect(object).toEqual({});",
			"assert.strictEqual(actual, expected);",
			"assert.ok(condition);",
			"assert.ok();",
			"expect(result).not.toBe(2);",
			"expect(1).not.toBe(1);",
			"expect(false).toBeTruthy();",
			"expect(false).not.toBeFalsy();",
			"expect(...values).toBe(true);",
			"expect(value).toBe(...args);",
			"other(1).toBe(1);",
			"assert.something(1, 1);",
			"assert.ok(value);",
			"foo.bar(1);",
			"const x = 1; let y = x; expect(y).toBe(1);",
			"const a = a;\nexpect(a).toBe(1);",
			"expect(!x).toBe(true);",
			"expect(+'a').toBe(0);",
			"expect(~1).toBe(-2);",
			"expect(typeof x).toBe('number');",
			"expect(true).not.toBe(true);",
			"expect({}).toBeNull();",
			"expect({}).toBeUndefined();",
			"expect({}).toBeFalsy();",
			"expect().toBe(1);",
			"expect(1).toBe();",
			"assert.ok();",
			"assert.strictEqual(1);",
			"assert.fail(1, 1);",
			"other.assert.ok(true);",
			"expect(1)[matcher](1);",
		],
	});

	ts.run("no-trivial-assertions typescript", rule, {
		invalid: [
			{
				code: "const flag = true as const;\nexpect(flag).toBe(true);",
				errors: [{ messageId: "issue" }],
			},
			{
				code: "const flag = true satisfies boolean;\nexpect(flag).toBe(true);",
				errors: [{ messageId: "issue" }],
			},
			{
				code: "const flag = true!;\nexpect(flag).toBe(true);",
				errors: [{ messageId: "issue" }],
			},
			{
				code: "const flag = <boolean>true;\nexpect(flag).toBe(true);",
				errors: [{ messageId: "issue" }],
			},
			{
				code: "const flag = true as boolean as boolean;\nexpect(flag).toBe(true);",
				errors: [{ messageId: "issue" }],
			},
		],
		valid: [
			"const result = compute();\nexpect(result).toBe(true);",
			"expect((value as number)).toBe(1);",
			"expect(value!).toBe(1);",
		],
	});
});
