import { describe, expect, it } from "vitest";

import { DICTIONARY_VERBS } from "$oxc-generated/dictionary-verbs";
import { getCandidateWords, isPrimarilyVerb, renderDictionaryVerbs } from "$script-utilities/dictionary-verbs";

describe("dictionary verb generation", () => {
	it("selects words missing from the programming list", () => {
		expect.assertions(1);

		expect(getCandidateWords(["throw", "get", "amount", "absorbedthe", "x-ray"], ["get"])).toStrictEqual([
			"absorbedthe",
			"amount",
			"throw",
		]);
	});

	it("accepts words whose most common part of speech is a verb", () => {
		expect.assertions(1);

		expect(isPrimarilyVerb([{ tags: ["query", "v", "n", "f:17.6"], word: "throw" }], "throw")).toBe(true);
	});

	it("rejects words whose most common part of speech is not a verb", () => {
		expect.assertions(2);

		expect(isPrimarilyVerb([{ tags: ["query", "n", "v"], word: "amount" }], "amount")).toBe(false);
		expect(isPrimarilyVerb([{ tags: ["query", "adj", "n", "v"], word: "total" }], "total")).toBe(false);
	});

	it("skips spelling corrections before the part of speech", () => {
		expect.assertions(1);

		expect(isPrimarilyVerb([{ tags: ["query", "spellcor:bounce", "v"], word: "debounce" }], "debounce")).toBe(true);
	});

	it("rejects responses that do not describe the queried word", () => {
		expect.assertions(5);

		expect(isPrimarilyVerb([], "throw")).toBe(false);
		expect(isPrimarilyVerb([{ tags: ["v"], word: "thrown" }], "throw")).toBe(false);
		expect(isPrimarilyVerb([{ word: "throw" }], "throw")).toBe(false);
		expect(isPrimarilyVerb({ error: "rate limited" }, "throw")).toBe(false);
		expect(isPrimarilyVerb([{ tags: [1, "v"], word: "throw" }], "throw")).toBe(true);
	});

	it("renders a sorted, deduplicated module that round-trips", () => {
		expect.assertions(2);

		const rendered = renderDictionaryVerbs(["throw", "get", "throw"]);

		expect(rendered).toContain('"get,throw".split(",")');
		expect(rendered).toMatch(/^\/\/ Generated by scripts\/generate-dictionary-verbs\.ts/u);
	});

	it("ships programming and dictionary verbs but not noun-first words", () => {
		expect.assertions(2);

		expect(DICTIONARY_VERBS).toStrictEqual(expect.arrayContaining(["await", "get", "throw"]));
		expect(DICTIONARY_VERBS).not.toStrictEqual(expect.arrayContaining(["amount"]));
	});
});
