// oxlint-disable small-rules/prevent-abbreviations -- not here, lol.

import nodePath from "node:path";
import { GLOB_DTS, GLOB_SRC, GLOB_SRC_EXT, GLOB_TESTS } from "@isentinel/eslint-config";
import { isentinel } from "@isentinel/eslint-config/oxlint";

import { baseIgnores, projectType } from "./constants.ts";

import type { OxfmtOptions } from "@isentinel/eslint-config";
import type { OxlintConfig, OxlintRules } from "@isentinel/eslint-config/oxlint";

const CONFIGURATION_FILES = `**/*.config.${GLOB_SRC_EXT}`;
const FIXTURES_FILES = `tests/fixtures/${GLOB_SRC}`;
const SCRIPT_FILES = `scripts/${GLOB_SRC}`;

interface ConfigurationOptions {
	readonly argv?: ReadonlyArray<string> | undefined;
	readonly rootDirectory: string;
	readonly tsconfigPath: string;
}

async function getOxfmtOptionsAsync(): Promise<OxfmtOptions> {
	const { getOxfmtConfigurationAsync } = await import("@howmanysmall/linter-utilities/configuration");
	return getOxfmtConfigurationAsync();
}

const reactTestRules: OxlintRules = {
	"react-perf/jsx-no-new-array-as-prop": "off",
	"react-perf/jsx-no-new-function-as-prop": "off",
	"react-perf/jsx-no-new-object-as-prop": "off",
	"react/no-multi-comp": "off",
	"react/no-unknown-property": "off",
	"react/only-export-components": "off",
};

export async function getOxlintAsync({
	argv,
	rootDirectory,
	tsconfigPath,
}: ConfigurationOptions): Promise<OxlintConfig> {
	const [allReactDoctorRules, oxfmtOptions] = await Promise.all([
		import("oxlint-plugin-react-doctor").then((library) => library.ALL_REACT_DOCTOR_RULES),
		getOxfmtOptionsAsync(),
	]);

	const reactDoctorRules = Object.fromEntries(
		Object.entries(allReactDoctorRules).map(([key, value]) => {
			if (key.includes("nextjs-") || key.includes("preact-") || key.includes("jsx-no-new-")) {
				return [key, "off" as const];
			}
			return [key, value];
		}),
	);

	return isentinel(
		{
			name: "small-rules",
			categories: {
				correctness: "error",
				nursery: "error",
				pedantic: "error",
				perf: "error",
				restriction: "error",
				style: "error",
				suspicious: "error",
			},
			componentExts: ["astro"],
			eslintPlugin: false,
			formatters: { oxfmtOptions },
			ignores: [
				...baseIgnores,
				"**/{dist,do-not-sync-ever,node_modules}/**",
				"scripts/clis/**/*.ts",
			] satisfies ReadonlyArray<string>,
			options: {
				denyWarnings: true,
				maxWarnings: 0,
				reportUnusedDisableDirectives: "error",
				respectEslintDisableDirectives: false,
				typeAware: true,
				typeCheck: argv === undefined ? true : !argv.includes("--lsp"),
			},
			react: {
				reactCompiler: true,
				version: "19.2.8",
			},
			roblox: false,
			rules: {
				"better-max-params/better-max-params": [
					"error",
					{
						constructor: 7,
						func: 7,
					},
				],
				"capitalized-comments": "off",
				"comment-length/limit-multi-line-comments": [
					"error",
					{
						semanticComments: ["v8 ignore"],
					},
				],
				"comment-length/limit-single-line-comments": [
					"error",
					{
						maxLength: 82,
						semanticComments: [
							"Modifications",
							"Vendored from",
							"oxlint-disable",
							"oxlint-disable-next-line",
							"biome-ignore",
							"eslint-disable-next-line",
						],
						tabSize: 4,
					},
				],
				complexity: ["error", { max: 20 }],
				curly: ["error", "multi-line"],
				"default-case": "off",
				// this is literally not true -- it just worsens performance!
				"e18e/prefer-static-collator": "off",
				"flawless/arrow-return-style": "off",
				"flawless/max-lines-per-function": "off",
				"func-style": [
					"error",
					"declaration",
					{
						allowArrowFunctions: false,
						allowTypeAnnotation: true,
						overrides: {
							namedExports: "ignore",
						},
					},
				],
				"import/exports-last": "off",
				"import/extensions": "off",
				"import/group-exports": "off",
				"import/max-dependencies": "off",
				"import/no-default-export": "off",
				"import/no-named-export": "off",
				"import/no-relative-parent-imports": "off",
				"import/no-unassigned-import": [
					"error",
					{
						allow: [
							"**/*.css",
							"**/*.scss",
							"**/*.less",
							"**/*.sass",
							"@total-typescript/ts-reset",
							"$configure-arktype",
							"$polyfill",
							"@dotenvx/dotenvx",
							"@dotenvx/dotenvx/config",
						],
					},
				],
				"import/prefer-default-export": "off",
				"init-declarations": "off",
				"jsdoc-js/convert-to-jsdoc-comments": [
					"warn",
					{
						allowedPrefixes: [
							"@ts-",
							"istanbul ",
							"c8 ",
							"v8 ",
							"eslint",
							"jshint",
							"jslint",
							"globals",
							"exported",
							"jscs",
							"oxlint-",
							"prettier-",
							"biome-ignore ",
						],
					},
				],
				"jsdoc/check-tag-names": [
					"error",
					{
						definedTags: ["expected-unused", "rejects"],
						jsxTags: false,
						typed: false,
					},
				],
				"jsdoc/require-param-type": "off",
				"jsdoc/require-property-type": "off",
				"jsdoc/require-returns-type": "off",
				"max-lines": "off",
				"max-lines-per-function": "off",
				"max-params": "off",
				"max-statements": "off",
				"new-cap": "off",
				"no-alert": "off",
				"no-bitwise": "off",
				"no-console": "off",
				"no-continue": "off",
				"no-duplicate-imports": "off",
				"no-magic-numbers": "off",
				"no-nested-ternary": "off",
				"no-plusplus": "off",
				"no-ternary": "off",
				"no-undefined": "off",
				"no-underscore-dangle": "off",
				"node-js/prefer-global/buffer": "off",
				"node/callback-return": "off",
				"node/no-sync": "off",
				"node/no-top-level-await": "off",
				"object-shorthand": ["error"],
				"one-var": "off",
				"oxc/no-async-await": "off",
				"oxc/no-const-enum": "off",
				"oxc/no-optional-chaining": "off",
				"oxc/no-rest-spread-properties": "off",
				"perfectionist/sort-modules": "off",
				"prefer-destructuring": "error",
				"prefer-named-capture-group": "off",
				"react-perf/jsx-no-new-function-as-prop": "off",
				"react/jsx-boolean-value": "off",
				"react/jsx-curly-brace-presence": [
					"error",
					{
						children: "always",
					},
				],
				"react/jsx-filename-extension": [
					"error",
					{
						extensions: ["jsx", "tsx"],
						ignoreFilesWithoutCode: true,
					},
				],
				"react/jsx-max-depth": ["error", { max: 4 }],
				"react/react-in-jsx-scope": "off",
				"small-rules/array-type-generic": "error",
				"small-rules/ban-instances": "off",
				"small-rules/ban-react-fc": "error",
				"small-rules/ban-types": [
					"off",
					{
						bannedTypes: {
							Omit: "Except",
						},
					},
				],
				"small-rules/consistent-compound-words": [
					"error",
					{
						allowList: {},
						checkProperties: false,
						checkShorthandProperties: false,
						checkVariables: false,
						extendDefaultReplacements: false,
						replacements: {},
					},
				],
				"small-rules/directive-disable-enable-pair": "error",
				"small-rules/directive-no-aggregating-enable": "error",
				"small-rules/directive-no-duplicate-disable": "error",
				"small-rules/directive-no-restricted-disable": "error",
				"small-rules/directive-no-unlimited-disable": "error",
				"small-rules/directive-no-unused-enable": "error",
				"small-rules/directive-no-use": "error",
				"small-rules/directive-require-description": [
					"error",
					{
						ignore: ["oxlint-enable"],
					},
				],
				"small-rules/enforce-ianitor-check-type": "off",
				"small-rules/isolated-functions": [
					"error",
					{
						comments: [],
						functions: [],
						overrideGlobals: {},
						selectors: [],
					},
				],
				"small-rules/memoized-effect-dependencies": "error",
				"small-rules/no-adjust-state-on-prop-change": "error",
				"small-rules/no-array-constructor-elements": [
					"error",
					{
						environment: "standard",
						requireExplicitGenericOnNewArray: true,
					},
				],
				"small-rules/no-array-constructor-index-assignment": "error",
				"small-rules/no-array-size-assignment": ["error", { allowAutofix: false }],
				"small-rules/no-async-in-system": "off",
				"small-rules/no-cascading-set-state": "error",
				"small-rules/no-chain-state-updates": "error",
				"small-rules/no-chained-type-assertions": "error",
				"small-rules/no-color3-constructor": "off",
				"small-rules/no-conditional-empty-object-spread": "error",
				"small-rules/no-constant-condition-with-break": [
					"error",
					{
						loopExitCalls: ["break", "return", "throw"],
					},
				],
				"small-rules/no-dead-store": "error",
				"small-rules/no-derived-state": "error",
				"small-rules/no-discarded-rejection": "warn",
				"small-rules/no-error": "off",
				"small-rules/no-event-handler": ["error", { environment: "standard" }],
				"small-rules/no-events-in-events-callback": "off",
				"small-rules/no-external-store-subscription": ["error", { environment: "standard" }],
				"small-rules/no-filter-map-chain": "error",
				"small-rules/no-floating-point-equality": "error",
				"small-rules/no-giant-component": "error",
				"small-rules/no-god-components": "off",
				"small-rules/no-has-before-remove-in-jecs": "off",
				"small-rules/no-ianitor-in-function-body": "off",
				"small-rules/no-ianitor-success-access": "off",
				"small-rules/no-identity-map": "error",
				"small-rules/no-increment-decrement": ["error", { allowAutofix: true }],
				"small-rules/no-initialize-state": ["error", { environment: "standard" }],
				"small-rules/no-inline-property-on-memo-component": "error",
				"small-rules/no-instance-methods-without-this": "off",
				"small-rules/no-known-value-widening": "error",
				"small-rules/no-module-mocking": "error",
				"small-rules/no-native-properties-spread": "off",
				"small-rules/no-new-instance-in-use-memo": "off",
				"small-rules/no-object-parameters": "error",
				"small-rules/no-pass-data-to-parent": ["error", { environment: "standard" }],
				"small-rules/no-pass-live-state-to-parent": ["error", { environment: "standard" }],
				"small-rules/no-print": "off",
				"small-rules/no-redundant-aspect-ratio-constraint": "off",
				"small-rules/no-reflect-apply": "error",
				"small-rules/no-reflect-get": "error",
				"small-rules/no-render-helper-functions": "error",
				"small-rules/no-reset-all-state-on-prop-change": ["error", { environment: "standard" }],
				"small-rules/no-restricted-property-assignment": "error",
				"small-rules/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
				"small-rules/no-shape-in-symbol-names": "error",
				"small-rules/no-spec-file-extension": "error",
				"small-rules/no-static-react-create-element": "error",
				"small-rules/no-table-create-map": "off",
				"small-rules/no-task-wait": "off",
				"small-rules/no-trivial-assertions": "error",
				"small-rules/no-underscore-react-props": "error",
				"small-rules/no-unknown-parameters": "error",
				"small-rules/no-unknown-returns": "error",
				"small-rules/no-unknown-type-aliases": "error",
				"small-rules/no-unsafe-dictionary-type": "error",
				"small-rules/no-unused-imports": "error",
				"small-rules/no-unused-use-memo": "error",
				"small-rules/no-use-memo-simple-expression": "error",
				"small-rules/no-useless-constants": "error",
				"small-rules/no-useless-default": "off",
				"small-rules/no-useless-use-effect": ["error", { environment: "standard" }],
				"small-rules/no-useless-use-memo": ["error", { environment: "standard" }],
				"small-rules/no-useless-use-spring": "off",
				"small-rules/no-variadic-spread": "error",
				"small-rules/no-warn": "off",
				"small-rules/no-widen-then-assert": "error",
				"small-rules/only-type-imports": "off",
				"small-rules/prefer-constant-dispatch": "error",
				"small-rules/prefer-context-stack": "off",
				"small-rules/prefer-direct-hook-imports": ["error", { environment: "standard" }],
				"small-rules/prefer-early-return": "error",
				"small-rules/prefer-expect-assertions": "off",
				"small-rules/prefer-hoisted-jsx-elements": "off",
				"small-rules/prefer-hoisted-jsx-object-properties": "off",
				"small-rules/prefer-idiv": "off",
				"small-rules/prefer-local-portal-component": "off",
				"small-rules/prefer-math-min-max": "off",
				"small-rules/prefer-membership-filter-in-jecs": "off",
				"small-rules/prefer-modding-inspect": "off",
				"small-rules/prefer-module-scope-constants": "off",
				"small-rules/prefer-native-collection-copy": "off",
				"small-rules/prefer-padding-components": "off",
				"small-rules/prefer-pascal-case-enums": "error",
				"small-rules/prefer-sequence-overloads": "off",
				"small-rules/prefer-single-world-query-in-jecs": "off",
				"small-rules/prefer-ternary-conditional-rendering": "error",
				"small-rules/prefer-udim2-shorthand": "off",
				"small-rules/prefer-use-reducer": "off",
				"small-rules/prevent-abbreviations": [
					"error",
					{
						allowPropertyAccess: [
							"char",
							"InstanceProps",
							"InferProps",
							"PropsWithoutRef",
							"ComponentProps",
							"screenProps",
							"getScreenProps",
							"PropsWithChildren",
							"args",
						],
						ignoreShorthands: ["InferProps", "InstanceProps", "PropsWithoutRef", "ComponentProps"],
						shorthands: {
							"*Props": "*Properties",
							"*props": "*properties",
							args: "parameters",
							btn: "button",
							char: "character",
							dt: "deltaTime",
							plr: "player",
							str: "string",
						},
					},
				],
				"small-rules/react-hooks-strict-return": "error",
				"small-rules/require-async-suffix": "error",
				"small-rules/require-module-level-instantiation": "off",
				"small-rules/require-named-effect-functions": "off",
				"small-rules/require-paired-calls": "error",
				"small-rules/require-react-component-keys": "off",
				"small-rules/require-react-display-names": ["error", { environment: "standard" }],
				"small-rules/require-safety-comment-for-type-assertion": "error",
				"small-rules/require-switch-case-braces": [
					"error",
					{
						metric: "lines",
					},
				],
				"small-rules/require-throw-error-capture": [
					"off",
					{
						allow: [{ name: "ValidationError", from: "package", package: "@cliffy/command" }],
					},
				],
				"small-rules/require-unicode-regex": "error",
				"small-rules/rerender-memo-with-default-value": "error",
				"small-rules/starts-with-verb": [
					"error",
					{
						allowList: ["increment", "decrement"],
					},
				],
				"small-rules/strict-component-boundaries": ["error", { allow: [] }],
				"small-rules/use-exhaustive-dependencies": "error",
				"small-rules/use-hook-at-top-level": "error",
				// shittier
				"sonar/destructuring-assignment-syntax": "off",
				"sonar/no-nested-incdec": "off",
				"sort-imports": [
					"off",
					{
						allowSeparatedGroups: true,
						ignoreCase: true,
						ignoreDeclarationSort: true,
						ignoreMemberSort: false,
					},
				],
				"sort-keys": [
					"off",
					"asc",
					{
						allowLineSeparatedGroups: true,
						caseSensitive: true,
						minKeys: 2,
						natural: true,
					},
				],
				"style/jsx-curly-brace-presence": "off",
				"style/padding-line-between-statements": [
					"error",
					{
						blankLine: "never",
						next: "*",
						prev: "directive",
					},
				],
				"ts/array-type": "off",
				"ts/explicit-member-accessibility": ["error", {}],
				"ts/prefer-readonly-parameter-types": "off",
				"ts/switch-exhaustiveness-check": [
					"error",
					{
						allowDefaultCaseForExhaustiveSwitch: true,
						considerDefaultExhaustiveForUnions: true,
						requireDefaultForNonUnion: false,
					},
				],
				"typescript/explicit-member-accessibility": ["error", {}],
				"unicorn-js/name-replacements": "off",
				"unicorn-js/no-break-in-nested-loop": "off",
				"unicorn-js/no-keyword-prefix": "off",
				"unicorn-js/no-unreadable-new-expression": "off",
				"unicorn-js/prefer-global-number-constants": "off",
				"unicorn/catch-error-name": ["warn", { name: "error" }],
				"unicorn/no-array-callback-reference": "off",
				"unicorn/no-new-array": "error",
				"unicorn/no-process-exit": "off",
				// shit rule that breaks everything:
				"unicorn/no-useless-undefined": "off",
				"unicorn/numeric-separators-style": "off",
				"unicorn/prefer-event-target": "off",
				"unicorn/prefer-math-trunc": "off",
				"unicorn/switch-case-braces": "off",
				"unused-imports/no-unused-vars": "off",
				"vue/no-dupe-keys": "off",
			},
			settings: {
				jsdoc: {
					tagNamePreference: {
						"expected-unused": "expected-unused",
					},
				},
				react: { version: "19.2.8" },
				"small-rules": { tsgolintVersion: "7.0.2002" },
				vitest: { typecheck: true },
			},
			spellCheck: false,
			stylistic: true,
			test: {
				vitest: {
					extended: true,
					files: GLOB_TESTS.filter((glob) => !glob.includes(".bench.")),
					typecheck: true,
				},
			},
			type: projectType,
			typescript: {
				outOfProjectFiles: ["*.js"],
				parserOptions: { tsconfigRootDir: nodePath.dirname(tsconfigPath) },
				tsconfigPath,
			},
		},
		{
			name: "small-rules/native-id-length",
			files: [GLOB_SRC],
			rules: {
				"eslint-js/id-length": "off",
				"id-length": [
					"error",
					{
						exceptionPatterns: ["^_"],
						exceptions: ["_", "x", "y", "z", "a", "b", "$"],
						max: 45,
					},
				],
			},
		},
		{
			name: "small-rules/react-doctor",
			files: [GLOB_SRC],
			jsPlugins: [{ name: "react-doctor", specifier: "oxlint-plugin-react-doctor" }],
			rules: {
				...reactDoctorRules,
				// STOP DUPLICATING NATIVE RULES!!!
				"react-doctor/forbid-component-props": "off",
				"react-doctor/jsx-boolean-value": "off",
				"react-doctor/jsx-curly-brace-presence": "off",
				"react-doctor/jsx-max-depth": "off",
				"react-doctor/jsx-no-new-array-as-prop": "off",
				"react-doctor/jsx-no-new-function-as-prop": "off",
				"react-doctor/jsx-no-new-object-as-prop": "off",
				"react-doctor/jsx-props-no-spreading": "off",
				"react-doctor/no-danger": "off",
				"react-doctor/no-multi-comp": "off",
				"react-doctor/no-unknown-property": "off",
				"react-doctor/only-export-components": "off",
				"react-doctor/react-in-jsx-scope": "off",
			},
			settings: {
				"react-doctor": { rootDirectory },
			},
		},
		{
			name: "small-rules/local-rules",
			files: [`src/${GLOB_SRC}`],
			jsPlugins: [{ name: "local", specifier: nodePath.join(rootDirectory, "tools/local-rules/index.ts") }],
			rules: { "local/prefer-node-type-constant": "error" },
		},
		{
			name: "small-rules/disable-stupid-rule",
			files: [
				// The file name is the Astro integration id, not the factory.
				"documentation/src/integrations/contextual-menu.ts",
				"src/rules/react/no-adjust-state-on-prop-change.ts",
				CONFIGURATION_FILES,
			],
			rules: { "sonar/file-name-differ-from-class": "off" },
		},
		{
			name: "small-rules/documentation",
			env: {
				astro: true,
				browser: true,
				node: true,
			},
			files: ["documentation/**/*"],
		},
		{
			name: "small-rules/allow-git",
			// rule-newness.ts spawns git to classify rules; the binary is a fixed
			// system dependency.
			files: ["documentation/src/data/rule-newness.ts"],
			rules: {
				"no-console": "off",
				"sonar/no-os-command-from-path": "off",
			},
		},
		{
			name: "small-rules/vitest",
			files: GLOB_TESTS.filter((glob) => !glob.includes(".bench.")),
			plugins: ["vitest"],
			rules: {
				"flawless/no-conditional-in-test": "off",
				"flawless/prefer-expect-assertions-count": "off",
				"max-lines": "off",
				"max-lines-per-function": "off",
				"no-console": "error",
				"small-rules/no-filter-map-chain": "off",
				"small-rules/prefer-expect-assertions": [
					"error",
					{
						additionalAssertionFunctions: ["expectRecord", "expectArray", "expectPresent"],
						additionalExpectCallNames: ["expectRecord", "expectArray", "expectPresent"],
					},
				],
				"small-rules/prevent-abbreviations": "off",
				"typescript/no-non-null-assertion": "off",
				"unicorn-js/no-incorrect-template-string-interpolation": "off",
				"unicorn/no-null": "off",
				"vitest/consistent-each-for": "error",
				"vitest/consistent-test-filename": "error",
				"vitest/consistent-test-it": "error",
				"vitest/consistent-vitest-vi": "error",
				"vitest/expect-expect": "error",
				"vitest/hoisted-apis-on-top": "error",
				"vitest/max-expects": "off",
				"vitest/max-nested-describe": "error",
				"vitest/no-alias-methods": "error",
				"vitest/no-commented-out-tests": "error",
				"vitest/no-conditional-expect": "error",
				"vitest/no-conditional-in-test": "error",
				"vitest/no-conditional-tests": "error",
				"vitest/no-disabled-tests": "error",
				"vitest/no-duplicate-hooks": "error",
				"vitest/no-focused-tests": "error",
				"vitest/no-hooks": "error",
				"vitest/no-identical-title": "error",
				"vitest/no-import-node-test": "error",
				"vitest/no-importing-vitest-globals": "off",
				"vitest/no-interpolation-in-snapshots": "error",
				"vitest/no-large-snapshots": "error",
				"vitest/no-mocks-import": "error",
				"vitest/prefer-called-exactly-once-with": "error",
				"vitest/prefer-called-once": "error",
				"vitest/prefer-called-times": "error",
				"vitest/prefer-describe-function-title": "off",
				"vitest/prefer-expect-assertions": "off",
				"vitest/prefer-expect-type-of": "error",
				"vitest/prefer-import-in-mock": "error",
				"vitest/prefer-importing-vitest-globals": "error",
				"vitest/prefer-strict-boolean-matchers": "error",
				"vitest/prefer-to-be-falsy": "off",
				"vitest/prefer-to-be-object": "error",
				"vitest/prefer-to-be-truthy": "off",
				"vitest/prefer-to-contain": "error",
				"vitest/prefer-todo": "error",
				"vitest/require-awaited-expect-poll": "error",
				"vitest/require-hook": "off",
				"vitest/require-local-test-context-for-concurrent-snapshots": "error",
				"vitest/require-mock-type-parameters": "error",
				"vitest/require-test-timeout": "off",
				"vitest/require-top-level-describe": "off",
				"vitest/valid-expect": "error",
				"vitest/valid-title": "error",
				"vitest/warn-todo": "error",
			},
		},
		{
			name: "small-rules/allow-top-level-await",
			files: ["documentation/**/*.astro", SCRIPT_FILES, CONFIGURATION_FILES],
			rules: { "node/no-top-level-await": "off" },
		},
		{
			name: "small-rules/astro",
			files: ["documentation/**/*.astro"],
			rules: {
				"import/unambiguous": "off",
				"small-rules/no-unused-imports": "off",
				"small-rules/prevent-abbreviations": "off",
				"sonar/unused-import": "off",
				"unused-imports/no-unused-imports": "off",
			},
		},
		{
			name: "small-rules/allow-console",
			files: [SCRIPT_FILES, CONFIGURATION_FILES],
			rules: { "no-console": "off" },
		},
		{
			name: "small-rules/these-are-fine",
			files: [CONFIGURATION_FILES],
			rules: {
				"small-rules/no-unsafe-dictionary-type": "off",
			},
		},
		{
			name: "small-rules/benchmarks",
			files: [`.benchmarks/${GLOB_SRC}`],
			rules: {
				"node/no-top-level-await": "off",
				"small-rules/no-runtime-typeof": "off",
				"small-rules/require-safety-comment-for-type-assertion": "off",
				"typescript/no-unsafe-type-assertion": "off",
			},
		},
		{
			name: "small-rules/allow-default-export",
			files: [FIXTURES_FILES, CONFIGURATION_FILES],
			rules: { "import/no-default-export": "off" },
		},
		{
			name: "small-rules-type-aware/allow-abbreviations",
			files: [FIXTURES_FILES, CONFIGURATION_FILES],
			rules: { "small-rules/prevent-abbreviations": "off" },
		},
		{
			name: "small-rules/allow-null",
			files: [
				"vitest*.config.ts",
				...GLOB_TESTS.filter((glob) => !glob.includes(".bench.")),
				"**/*.tsx",
			] satisfies ReadonlyArray<string>,
			rules: { "unicorn/no-null": "off" },
		},
		{
			name: "small-rules/fixtures",
			files: [FIXTURES_FILES],
			rules: {
				...reactTestRules,
				"eslint-js/no-restricted-syntax": "off",
				"small-rules/no-unknown-parameters": "off",
				"small-rules/no-unknown-returns": "off",
				"small-rules/no-unsafe-dictionary-type": "off",
				"typescript/ban-ts-comment": "off",
			},
		},
		{
			name: "small-rules/documentation-react-tests",
			files: ["documentation/tests/**/*.test.tsx"],
			rules: reactTestRules,
		},
		{
			name: "small-rules/allow-unambiguous-import",
			files: [GLOB_DTS],
			rules: { "import/unambiguous": "off" },
		},
		{
			name: "small-rules/react",
			files: ["documentation/src/**/*.{ts,tsx}"],
			plugins: ["react", "react-perf", "jsx-a11y"],
			rules: {
				"react-perf/jsx-no-new-function-as-prop": "off",
				"react/jsx-curly-brace-presence": [
					"error",
					{
						children: "always",
					},
				],
				"react/jsx-filename-extension": [
					"error",
					{
						extensions: ["jsx", "tsx"],
						ignoreFilesWithoutCode: true,
					},
				],
				"react/jsx-max-depth": ["error", { max: 3 }],
				"small-rules/ban-react-fc": "error",
				"small-rules/memoized-effect-dependencies": ["error", { environment: "standard" }],
				"small-rules/no-adjust-state-on-prop-change": ["error", { environment: "standard" }],
				"small-rules/no-cascading-set-state": "error",
				"small-rules/no-chain-state-updates": ["error", { environment: "standard" }],
				"small-rules/no-derived-state": ["error", { environment: "standard" }],
				"small-rules/no-event-handler": ["error", { environment: "standard" }],
				"small-rules/no-external-store-subscription": ["error", { environment: "standard" }],
				"small-rules/no-giant-component": "error",
				"small-rules/no-god-components": "off",
				"small-rules/no-initialize-state": ["error", { environment: "standard" }],
				"small-rules/no-inline-property-on-memo-component": "error",
				"small-rules/no-pass-data-to-parent": ["error", { environment: "standard" }],
				"small-rules/no-pass-live-state-to-parent": ["error", { environment: "standard" }],
				"small-rules/no-render-helper-functions": "error",
				"small-rules/no-reset-all-state-on-prop-change": ["error", { environment: "standard" }],
				"small-rules/no-static-react-create-element": ["error", { environment: "standard" }],
				"small-rules/no-underscore-react-props": "error",
				"small-rules/no-unused-use-memo": [
					"error",
					{
						environment: "standard",
					},
				],
				"small-rules/no-use-memo-simple-expression": "error",
				"small-rules/no-useless-default": "error",
				"small-rules/no-useless-use-effect": ["error", { environment: "standard" }],
				"small-rules/no-useless-use-memo": ["error", { environment: "standard" }],
				"small-rules/prefer-constant-dispatch": "error",
				"small-rules/prefer-direct-hook-imports": ["error", { environment: "standard" }],
				"small-rules/prefer-hoisted-jsx-elements": [
					"off",
					{
						additionalHoistableComponents: [],
						additionalStaticFactories: [],
						environment: "standard",
					},
				],
				"small-rules/prefer-hoisted-jsx-object-properties": "off",
				"small-rules/prefer-use-reducer": "error",
				"small-rules/react-hooks-strict-return": "error",
				"small-rules/require-named-effect-functions": [
					"error",
					{
						environment: "standard",
						hooks: [
							{ name: "useEffect", allowAsync: false },
							{ name: "useLayoutEffect", allowAsync: false },
							{ name: "useInsertionEffect", allowAsync: false },
						],
					},
				],
				"small-rules/require-react-display-names": ["error", { environment: "standard" }],
				"small-rules/rerender-memo-with-default-value": "error",
				"small-rules/use-exhaustive-dependencies": "error",
				"small-rules/use-hook-at-top-level": "error",
			},
		},
		{
			name: "small-rules/allow-complexity",
			files: ["tests/rule-harness/**", "scripts/**"],
			rules: { complexity: "off" },
		},
	);
}
