// oxlint-disable small-rules/no-unknown-parameters -- parses the raw Datamuse response
import { Predicate } from "effect";

const PARTS_OF_SPEECH = new Set(["adj", "adv", "n", "u", "v"]);
const LOWERCASE_WORD = /^[a-z]+$/u;

export function getCandidateWords(
	completeVerbs: ReadonlyArray<string>,
	programmingVerbs: ReadonlyArray<string>,
): ReadonlyArray<string> {
	const programming = new Set(programmingVerbs);
	return completeVerbs
		.filter((word) => !programming.has(word) && LOWERCASE_WORD.test(word))
		.toSorted((left, right) => left.localeCompare(right));
}

/**
 * Checks a Datamuse `md=p` response, whose part-of-speech tags are ordered by
 * likelihood, for a word that is used as a verb more often than anything else.
 *
 * @param response - The parsed Datamuse response body.
 * @param word - The word that was queried.
 * @returns Whether the word's most common part of speech is a verb.
 */
export function isPrimarilyVerb(response: unknown, word: string): boolean {
	if (!Array.isArray(response)) return false;

	const [hit]: ReadonlyArray<unknown> = response;
	if (!Predicate.isObject(hit) || !("word" in hit) || hit.word !== word) return false;
	if (!("tags" in hit) || !Array.isArray(hit.tags)) return false;

	for (const tag of hit.tags) {
		if (Predicate.isString(tag) && PARTS_OF_SPEECH.has(tag)) return tag === "v";
	}
	return false;
}

export function renderDictionaryVerbs(words: ReadonlyArray<string>): string {
	const sorted = [...new Set(words)].toSorted((left, right) => left.localeCompare(right));
	return [
		"// Generated by scripts/generate-dictionary-verbs.ts from verb-corpus and Datamuse part-of-speech tags.",
		`export const DICTIONARY_VERBS: ReadonlyArray<string> = "${sorted.join(",")}".split(",");`,
		"",
	].join("\n");
}
