interface RobloxClass {
	readonly members: ReadonlyArray<unknown>;
	readonly name: string;
	readonly superclass: string;
}

export interface YieldingMemberCatalog {
	readonly classes: ReadonlySet<string>;
	readonly instanceMembers: ReadonlyArray<string>;
	readonly yieldingMembers: ReadonlyMap<string, ReadonlyArray<string>>;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}

function parseClass(value: unknown): RobloxClass | undefined {
	if (!isRecord(value) || typeof value.Name !== "string" || typeof value.Superclass !== "string") return undefined;
	if (!Array.isArray(value.Members)) return undefined;
	return { members: value.Members, name: value.Name, superclass: value.Superclass };
}

function isYieldingFunction(value: unknown): value is Record<string, unknown> & { readonly Name: string } {
	if (!isRecord(value) || value.MemberType !== "Function" || typeof value.Name !== "string") return false;
	return Array.isArray(value.Tags) && value.Tags.some((tag) => tag === "Yields" || tag === "CanYield");
}

export function parseClasses(value: unknown): ReadonlyMap<string, RobloxClass> {
	if (!(isRecord(value) && Array.isArray(value.Classes))) {
		const error = new TypeError("Roblox API dump has no Classes array.");
		Error.captureStackTrace(error, parseClasses);
		throw error;
	}

	const classes = new Map<string, RobloxClass>();
	for (const classValue of value.Classes) {
		const classDefinition = parseClass(classValue);
		if (classDefinition !== undefined) classes.set(classDefinition.name, classDefinition);
	}
	return classes;
}

export function createYieldingMemberCatalog(classes: ReadonlyMap<string, RobloxClass>): YieldingMemberCatalog {
	const directMembers = new Map<string, ReadonlyArray<string>>();
	for (const [className, classDefinition] of classes) {
		directMembers.set(
			className,
			classDefinition.members.filter(isYieldingFunction).map((member) => member.Name),
		);
	}

	const cache = new Map<string, ReadonlyArray<string>>();
	function collectMembers(className: string): ReadonlyArray<string> {
		const cached = cache.get(className);
		if (cached !== undefined) return cached;
		const classDefinition = classes.get(className);
		if (classDefinition === undefined) return [];
		const inherited = collectMembers(classDefinition.superclass);
		const members = [...new Set([...inherited, ...(directMembers.get(className) ?? [])])].toSorted();
		cache.set(className, members);
		return members;
	}

	const instanceMembers = collectMembers("Instance");
	const yieldingMembers = new Map<string, ReadonlyArray<string>>();
	for (const className of classes.keys()) {
		const members = collectMembers(className).filter((member) => !instanceMembers.includes(member));
		if (members.length > 0) yieldingMembers.set(className, members);
	}

	return { classes: new Set(classes.keys()), instanceMembers, yieldingMembers };
}

export function catalogHasYieldingMember(
	catalog: YieldingMemberCatalog,
	className: string,
	memberName: string,
): boolean {
	if (!catalog.classes.has(className)) return false;
	return (
		catalog.instanceMembers.includes(memberName) ||
		catalog.yieldingMembers.get(className)?.includes(memberName) === true
	);
}

export function renderCatalog(classes: ReadonlyMap<string, RobloxClass>): string {
	const catalog = createYieldingMemberCatalog(classes);
	const yieldingMembers = Object.fromEntries(
		[...catalog.yieldingMembers]
			.toSorted(([left], [right]) => left.localeCompare(right))
			.map(([className, members]) => [className, members.join(",")]),
	);

	return `// Generated by scripts/generate-roblox-yielding-members.ts from the latest Roblox Client Tracker API dump.
const ROBLOX_CLASSES = new Set(${JSON.stringify([...catalog.classes].toSorted().join(","))}.split(","));
const ROBLOX_INSTANCE_YIELDING_MEMBERS = new Set(${JSON.stringify(catalog.instanceMembers.join(","))}.split(","));
const ROBLOX_YIELDING_MEMBERS: Readonly<Record<string, string>> = ${JSON.stringify(yieldingMembers)};

export function classHasYieldingMember(className: string, memberName: string): boolean {
	if (!ROBLOX_CLASSES.has(className)) return false;
	if (ROBLOX_INSTANCE_YIELDING_MEMBERS.has(memberName)) return true;
	return ROBLOX_YIELDING_MEMBERS[className]?.split(",").includes(memberName) === true;
}
`;
}
