import { Predicate } from "effect";

import type { JsonObject, JsonValue } from "type-fest";

interface RobloxClass {
	readonly name: string;
	readonly members: ReadonlyArray<JsonValue>;
	readonly superclass: string;
}

type RobloxApiValue = ReturnType<typeof JSON.parse>;

export interface YieldingMemberCatalog {
	readonly classes: ReadonlySet<string>;
	readonly instanceMembers: ReadonlyArray<string>;
	readonly yieldingMembers: ReadonlyMap<string, ReadonlyArray<string>>;
}

function isRecord(value: RobloxApiValue): value is JsonObject {
	return Predicate.isObject(value) && !Array.isArray(value);
}

function parseClass(value: RobloxApiValue): RobloxClass | undefined {
	if (!isRecord(value) || !Predicate.isString(value.Name) || !Predicate.isString(value.Superclass)) return undefined;
	if (!Array.isArray(value.Members)) return undefined;
	return { name: value.Name, members: value.Members, superclass: value.Superclass };
}

function isYieldingFunction(value: RobloxApiValue): value is JsonObject & { readonly Name: string } {
	if (!isRecord(value) || value.MemberType !== "Function" || !Predicate.isString(value.Name)) return false;
	return Array.isArray(value.Tags) && value.Tags.some((tag) => tag === "Yields" || tag === "CanYield");
}

export function parseClasses(value: RobloxApiValue): ReadonlyMap<string, RobloxClass> {
	if (!isRecord(value) || !Array.isArray(value.Classes)) {
		const error = new TypeError("Roblox API dump has no Classes array.");
		Error.captureStackTrace(error, parseClasses);
		throw error;
	}

	const classes = new Map<string, RobloxClass>();
	for (const classValue of value.Classes) {
		const classDefinition = parseClass(classValue);
		if (classDefinition !== undefined) classes.set(classDefinition.name, classDefinition);
	}
	return classes;
}

export function createYieldingMemberCatalog(classes: ReadonlyMap<string, RobloxClass>): YieldingMemberCatalog {
	const directMembers = new Map<string, ReadonlyArray<string>>();
	for (const [className, classDefinition] of classes) {
		directMembers.set(
			className,
			classDefinition.members.filter(isYieldingFunction).map((member) => member.Name),
		);
	}

	const cache = new Map<string, ReadonlyArray<string>>();
	function collectMembers(className: string): ReadonlyArray<string> {
		const cached = cache.get(className);
		if (cached !== undefined) return cached;
		const classDefinition = classes.get(className);
		if (classDefinition === undefined) return [];
		const inherited = collectMembers(classDefinition.superclass);
		const members = [...new Set([...inherited, ...(directMembers.get(className) ?? [])])].toSorted();
		cache.set(className, members);
		return members;
	}

	const instanceMembers = collectMembers("Instance");
	const yieldingMembers = new Map<string, ReadonlyArray<string>>();
	for (const className of classes.keys()) {
		const members = collectMembers(className).filter((member) => !instanceMembers.includes(member));
		if (members.length > 0) yieldingMembers.set(className, members);
	}

	return { classes: new Set(classes.keys()), instanceMembers, yieldingMembers };
}

export function catalogHasYieldingMember(
	catalog: YieldingMemberCatalog,
	className: string,
	memberName: string,
): boolean {
	if (!catalog.classes.has(className)) return false;
	return (
		catalog.instanceMembers.includes(memberName) ||
		catalog.yieldingMembers.get(className)?.includes(memberName) === true
	);
}

export function renderCatalog(classes: ReadonlyMap<string, RobloxClass>): string {
	const catalog = createYieldingMemberCatalog(classes);
	const classNames = [...catalog.classes].toSorted();
	const yieldingMembers = [...catalog.yieldingMembers].toSorted(
		([left], [right]) => classNames.indexOf(left) - classNames.indexOf(right),
	);
	const memberGroupCounts = new Map<string, number>();
	for (const [, members] of yieldingMembers) {
		const memberGroup = members.join(",");
		memberGroupCounts.set(memberGroup, (memberGroupCounts.get(memberGroup) ?? 0) + 1);
	}

	const sharedMemberGroups = [...memberGroupCounts]
		.filter(([, count]) => count > 1)
		.map(([memberGroup]) => memberGroup)
		.toSorted((left, right) => left.localeCompare(right));
	const sharedMemberGroupIndexes = new Map(sharedMemberGroups.map((memberGroup, index) => [memberGroup, index]));
	const yieldingMemberEntries = yieldingMembers
		.map(([className, members]) => {
			const classIndex = classNames.indexOf(className);
			const memberGroup = members.join(",");
			const sharedIndex = sharedMemberGroupIndexes.get(memberGroup);
			const value =
				sharedIndex === undefined
					? JSON.stringify(memberGroup)
					: `ROBLOX_YIELDING_MEMBER_GROUPS[${sharedIndex}]`;
			return `[${classIndex},${value}]`;
		})
		.join(",");

	return `// Generated by scripts/generate-roblox-yielding-members.ts from the latest Roblox Client Tracker API dump.
const ROBLOX_CLASS_INDEXES = new Map(${JSON.stringify(classNames.join(","))}.split(",").map((className, classIndex) => [className, classIndex]));
const ROBLOX_INSTANCE_YIELDING_MEMBERS = new Set(${JSON.stringify(catalog.instanceMembers.join(","))}.split(","));
const ROBLOX_YIELDING_MEMBER_GROUPS = ${JSON.stringify(sharedMemberGroups)} as const;
const ROBLOX_YIELDING_MEMBERS = new Map<number, string>([${yieldingMemberEntries}]);
const ROBLOX_YIELDING_MEMBER_SETS = new Map<number, ReadonlySet<string>>();

export function classHasYieldingMember(className: string, memberName: string): boolean {
	const classIndex = ROBLOX_CLASS_INDEXES.get(className);
	if (classIndex === undefined) return false;
	if (ROBLOX_INSTANCE_YIELDING_MEMBERS.has(memberName)) return true;

	const cached = ROBLOX_YIELDING_MEMBER_SETS.get(classIndex);
	if (cached !== undefined) return cached.has(memberName);

	const packed = ROBLOX_YIELDING_MEMBERS.get(classIndex);
	if (packed === undefined) return false;

	const members: ReadonlySet<string> = new Set(packed.split(","));
	ROBLOX_YIELDING_MEMBER_SETS.set(classIndex, members);
	return members.has(memberName);
}
`;
}
