#!/usr/bin/env nub

import { argv } from "node:process";
import { Command } from "@cliffy/command";

const allCreatableInstances = [
	"accessory",
	"accessorydescription",
	"accoutrement",
	"actor",
	"adgui",
	"adportal",
	"aircontroller",
	"alignorientation",
	"alignposition",
	"angularvelocity",
	"animation",
	"animationconstraint",
	"animationcontroller",
	"animationgraphdefinition",
	"animationnodedefinition",
	"animationrigdata",
	"animator",
	"annotation",
	"archandles",
	"atmosphere",
	"atmospheresensor",
	"attachment",
	"audioanalyzer",
	"audiochannelmixer",
	"audiochannelsplitter",
	"audiochorus",
	"audiocompressor",
	"audiodeviceinput",
	"audiodeviceoutput",
	"audiodistortion",
	"audioecho",
	"audioemitter",
	"audioequalizer",
	"audiofader",
	"audiofilter",
	"audioflanger",
	"audiogate",
	"audiolimiter",
	"audiolistener",
	"audiopitchshifter",
	"audioplayer",
	"audiorecorder",
	"audioreverb",
	"audiosearchparams",
	"audiospeechtotext",
	"audiotexttospeech",
	"audiotremolo",
	"aurorascript",
	"avatarabilityrules",
	"avataraccessoryrules",
	"avataranimationrules",
	"avatarbodyrules",
	"avatarclothingrules",
	"avatarcollisionrules",
	"avatarrules",
	"backpack",
	"ballsocketconstraint",
	"beam",
	"billboardgui",
	"bindableevent",
	"bindablefunction",
	"blockmesh",
	"bloomeffect",
	"blureffect",
	"bodyangularvelocity",
	"bodycolors",
	"bodyforce",
	"bodygyro",
	"bodypartdescription",
	"bodyposition",
	"bodythrust",
	"bodyvelocity",
	"bone",
	"boolvalue",
	"boxhandleadornment",
	"breakpoint",
	"brickcolorvalue",
	"bubblechatmessageproperties",
	"buoyancysensor",
	"camera",
	"canvasgroup",
	"cframevalue",
	"charactermesh",
	"chorussoundeffect",
	"clickdetector",
	"climbcontroller",
	"clouds",
	"color3value",
	"colorcorrectioneffect",
	"colorgradingeffect",
	"compositevaluecurve",
	"compressorsoundeffect",
	"conehandleadornment",
	"configuration",
	"controllermanager",
	"controllerpartsensor",
	"cornerwedgepart",
	"curveanimation",
	"customlog",
	"cylinderhandleadornment",
	"cylindermesh",
	"cylindricalconstraint",
	"datastoregetoptions",
	"datastoreincrementoptions",
	"datastoreoptions",
	"datastoresetoptions",
	"decal",
	"depthoffieldeffect",
	"dialog",
	"dialogchoice",
	"digitsrigdescription",
	"distortionsoundeffect",
	"doubleconstrainedvalue",
	"dragdetector",
	"dragger",
	"echosoundeffect",
	"equalizersoundeffect",
	"eulerrotationcurve",
	"experienceinviteoptions",
	"explorerfilter",
	"explosion",
	"facecontrols",
	"filemesh",
	"fire",
	"flangesoundeffect",
	"floatcurve",
	"floorwire",
	"fluidforcesensor",
	"folder",
	"forcefield",
	"frame",
	"generatedfolder",
	"gettextboundsparams",
	"glue",
	"groundcontroller",
	"handles",
	"hapticeffect",
	"hat",
	"hiddensurfaceremovalasset",
	"highlight",
	"hingeconstraint",
	"hole",
	"humanoid",
	"humanoidcontroller",
	"humanoiddescription",
	"humanoidrigdescription",
	"ikcontrol",
	"imagebutton",
	"imagehandleadornment",
	"imagelabel",
	"inputaction",
	"inputbinding",
	"inputcontext",
	"intconstrainedvalue",
	"internalsyncitem",
	"intersectoperation",
	"intvalue",
	"keyframe",
	"keyframemarker",
	"keyframesequence",
	"linearvelocity",
	"lineforce",
	"linehandleadornment",
	"localizationtable",
	"localscript",
	"makeupdescription",
	"manualglue",
	"manualweld",
	"markercurve",
	"materialvariant",
	"meshpart",
	"model",
	"modulescript",
	"motor",
	"motor6d",
	"motorfeature",
	"negateoperation",
	"nocollisionconstraint",
	"noise",
	"numberpose",
	"numbervalue",
	"objectvalue",
	"operationgraph",
	"pants",
	"part",
	"particleemitter",
	"partoperation",
	"path2d",
	"pathfindinglink",
	"pathfindingmodifier",
	"pitchshiftsoundeffect",
	"plane",
	"planeconstraint",
	"pluginaction",
	"plugincapabilities",
	"pointlight",
	"pose",
	"prismaticconstraint",
	"proceduralmodel",
	"proximityprompt",
	"pyramidhandleadornment",
	"rayvalue",
	"realtimemedia",
	"relativegui",
	"remoteevent",
	"remotefunction",
	"renderingtest",
	"reverbsoundeffect",
	"rigidconstraint",
	"rocketpropulsion",
	"rodconstraint",
	"ropeconstraint",
	"rotate",
	"rotatep",
	"rotatev",
	"rotationcurve",
	"rtanimationtracker",
	"screengui",
	"script",
	"scrollingframe",
	"seat",
	"selectionbox",
	"selectionpartlasso",
	"selectionpointlasso",
	"selectionsphere",
	"shirt",
	"shirtgraphic",
	"skateboardcontroller",
	"skateboardplatform",
	"sky",
	"smoke",
	"snap",
	"sound",
	"soundgroup",
	"sparkles",
	"spawnlocation",
	"specialmesh",
	"spherehandleadornment",
	"spotlight",
	"springconstraint",
	"startergear",
	"stringvalue",
	"studioattachment",
	"studiocallout",
	"stylederive",
	"stylelink",
	"stylequery",
	"stylerule",
	"stylesheet",
	"sunrayseffect",
	"surfaceappearance",
	"surfacegui",
	"surfacelight",
	"surfaceselection",
	"swimcontroller",
	"team",
	"teleportoptions",
	"terraindetail",
	"terrainregion",
	"textbox",
	"textbutton",
	"textchannel",
	"textchatcommand",
	"textchatmessageproperties",
	"textgenerator",
	"textlabel",
	"texture",
	"tool",
	"torque",
	"torsionspringconstraint",
	"trackerstreamanimation",
	"trail",
	"tremolosoundeffect",
	"trusspart",
	"uiaspectratioconstraint",
	"uicorner",
	"uidragdetector",
	"uiflexitem",
	"uigradient",
	"uigridlayout",
	"uilistlayout",
	"uipadding",
	"uipagelayout",
	"uiscale",
	"uishadow",
	"uisizeconstraint",
	"uistroke",
	"uitablelayout",
	"uitextsizeconstraint",
	"unionoperation",
	"universalconstraint",
	"unreliableremoteevent",
	"valuecurve",
	"vector3curve",
	"vector3value",
	"vectorforce",
	"vehiclecontroller",
	"vehicleseat",
	"velocitymotor",
	"videodeviceinput",
	"videodisplay",
	"videoframe",
	"videoplayer",
	"viewportframe",
	"visualizationmode",
	"visualizationmodecategory",
	"wedgepart",
	"weld",
	"weldconstraint",
	"wire",
	"wireframehandleadornment",
	"workspaceannotation",
	"worldmodel",
	"wrapdeformer",
	"wraplayer",
	"wraptarget",
	"wraptexturetransfer",
] as const;

const excludedClassNames = new Set([
	"accessory",
	"accessorydescription",
	"accoutrement",
	"actor",
	"aircontroller",
	"animationrigdata",
	"annotation",
	"atmosphere",
	"atmospheresensor",
	"audiosearchparams",
	"backpack",
	"bindableevent",
	"bindablefunction",
	"breakpoint",
	"bubblechatmessageproperties",
	"buoyancysensor",
	"climbcontroller",
	"clouds",
	"controllermanager",
	"controllerpartsensor",
	"datastoregetoptions",
	"datastoreincrementoptions",
	"datastoreoptions",
	"datastoresetoptions",
	"dialog",
	"dialogchoice",
	"experienceinviteoptions",
	"explorerfilterinstance",
	"explosion",
	"fluidforcesensor",
	"gettextboundsparams",
	"glue",
	"groundcontroller",
	"hat",
	"hiddensurfaceremovalasset",
	"hole",
	"internalsyncitem",
	"intersectoperation",
	"keyframe",
	"keyframemarker",
	"keyframesequence",
	"localscript",
	"manualglue",
	"manualweld",
	"markercurve",
	"modulescript",
	"negateoperation",
	"operationgraph",
	"partoperation",
	"pathfindinglink",
	"pathfindingmodifier",
	"plane",
	"plugincapabilities",
	"pose",
	"remoteevent",
	"remotefunction",
	"rtanimationtracker",
	"script",
	"skateboardcontroller",
	"skateboardplatform",
	"snap",
	"spawnlocation",
	"startergear",
	"studioattachment",
	"studiocallout",
	"surfaceselection",
	"swimcontroller",
	"team",
	"teleportoptions",
	"terraindetail",
	"terrainregion",
	"textchannel",
	"textchatcommand",
	"textchatmessageproperties",
	"trackerstreamanimation",
	"unionoperation",
	"unreliableremoteevent",
	"vehiclecontroller",
	"videodeviceinput",
	"visualizationmode",
	"visualizationmodecategory",
	"workspaceannotation",
] as const);

function toLowerCase<TString extends string>(value: TString): Lowercase<TString> {
	// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- wrong!
	return value.toLowerCase() as Lowercase<TString>;
}

function getRbxTsReactInstances(): ReadonlyArray<string> {
	return allCreatableInstances.filter((value) => !excludedClassNames.has(value));
}

async function getLoadedClassesAsync(
	classes?: ReadonlyArray<string>,
	loadClassesFrom?: string,
): Promise<ReadonlySet<string>> {
	if (classes !== undefined && classes.length > 0) return new Set(classes.map(toLowerCase));

	if (loadClassesFrom !== undefined && loadClassesFrom.length > 0) {
		const { existsAsync } = await import("$script-utilities/file-system-utilities");
		const directoryExists = await existsAsync(loadClassesFrom);
		if (directoryExists) {
			const { scanDirectoryAsync, ScanType } = await import("$script-utilities/instance-utilities");
			const instances = await scanDirectoryAsync(loadClassesFrom, ScanType.Both);
			return new Set(instances.map(toLowerCase));
		}
	}

	return new Set(getRbxTsReactInstances());
}

const command = new Command()
	.name("generate-default-properties")
	.version("1.0.0")
	.description(
		"Generates a structured JSON map of Roblox class default properties for the useless-default Oxlint rule.",
	)
	.env("GITHUB_TOKEN=<value:string>", "The GitHub token environment variable.", { required: false })
	.env("GITHUB_PAT=<value:string>", "Alternative GitHub token environment variable.", { required: false })
	.env("GITHUB_PERSONAL_ACCESS_TOKEN=<value:string>", "Alternative GitHub token environment variable.", {
		required: false,
	})
	.option("-o, --output <output-path:string>", "Write JSON output to a file instead of stdout.")
	.option("-p, --pretty", "Pretty-print JSON with indentation.")
	.option("--force-latest", "Force use of the latest database version.", {
		conflicts: ["file-path"],
	})
	.option("-q, --quiet", "Suppress warning output for unmapped property types.")
	.option("-c, --classes <class-names:string...>", "Only include the specified class. Can be used multiple times.", {
		conflicts: ["load-classes-from"],
	})
	.option(
		"-l, --load-classes-from <directory:string>",
		"Load the classes automatically in a way akin to what scan-roblox-instances does.",
		{ conflicts: ["classes"] },
	)
	.option("--file-path <file-path:file>", "The path to the msgpack database.", {
		conflicts: ["force-latest"],
	})
	.action(
		async ({
			classes,
			filePath,
			forceLatest,
			loadClassesFrom,
			output,
			pretty,
			quiet,
			githubToken,
			githubPat,
			githubPersonalAccessToken,
		}) => {
			const { Octokit } = await import("@octokit/rest");
			const octokit = new Octokit({
				// oxlint-disable-next-line typescript/strict-boolean-expressions typescript/prefer-nullish-coalescing -- no?
				auth: githubToken || githubPat || githubPersonalAccessToken,
			});

			const databaseUtilities = await import("$script-utilities/database-utilities");
			const { downloadDatabaseAsync, extractDefaults, parseDatabase } = databaseUtilities;

			const databaseBuffer = await downloadDatabaseAsync(octokit, forceLatest === true ? undefined : filePath);
			const filterSet = await getLoadedClassesAsync(classes, loadClassesFrom);

			const { decode } = await import("@std/msgpack");

			const outputData = {
				classes: extractDefaults(parseDatabase(decode(databaseBuffer), filterSet), {
					filterClasses: [...filterSet],
					quiet,
				}),
				version: 1,
			};

			const json = JSON.stringify(outputData, undefined, pretty ? 2 : undefined);
			if (output === undefined) console.log(json);
			else {
				const { mkdir, writeFile } = await import("node:fs/promises");
				const { dirname } = await import("node:path");
				await mkdir(dirname(output), { recursive: true });
				await writeFile(output, json, "utf8");
				console.log(`Wrote ${json.length} bytes to ${output}`);
			}
		},
	);

await command.parse(argv.slice(2));
