name: Checks

on:
  workflow_call:

permissions: {}

jobs:
  check:
    name: Validate
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup toolchain
        uses: ./.github/actions/setup

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Biome
        run: node --run biome -- ci

      - name: oxfmt
        run: node --run oxfmt -- --check

      - name: Lint
        run: node --run oxlint

      - name: Type Check
        run: node --run type-check

      - name: Knip
        run: node --run knip

      - name: Build
        run: node --run build -- --minify && test -f dist/index.js

  documentation:
    name: Documentation
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup toolchain
        uses: ./.github/actions/setup
        with:
          tools: bun node pnpm ni

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Type check documentation
        run: node --run check
        working-directory: documentation

      - name: Install Chromium
        run: pnpm --filter docs exec playwright install --with-deps chromium

      - name: Build documentation
        run: node --run build
        working-directory: documentation

      - name: Test React components
        run: node --run test:unit
        working-directory: documentation

      - name: Test documentation in Chromium
        run: node --run test:browser
        working-directory: documentation

  test:
    name: Test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup toolchain
        uses: ./.github/actions/setup

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Run tests
        run: node --run test -- --reporter github-actions --reporter dot
