// oxlint-disable-next-line comment-length/limit-single-line-comments -- harper:ignore
// Generated by running `rush-cli json-schema arktype node_modules/oxfmt/configuration_schema.json --stdout --allow-remote-refs --name OxfmtConfiguration`

import { isBoolean, isInteger, isReadonlyArrayOfStrings, isString, isUnknown } from "@small-rules/arktype-utilities";
import { type } from "arktype";

const isArrowParensConfiguration = type("'always' | 'avoid'");
const isCommentLineStrategyConfiguration = type("'singleLine' | 'multiline' | 'keep'");
const isEmbeddedLanguageFormattingConfiguration = type("'auto' | 'off'");
const isEndOfLineConfiguration = type("'lf' | 'crlf' | 'cr'");
const isHtmlWhitespaceSensitivityConfiguration = type("'css' | 'strict' | 'ignore'");

const isImportModifierConfiguration = type("'side_effect' | 'type' | 'value' | 'default' | 'wildcard' | 'named'");

const isImportSelectorConfiguration = type(
	"'type' | 'side_effect_style' | 'side_effect' | 'style' | 'index' | 'sibling' | 'parent' | 'subpath' | 'internal' | 'builtin' | 'external' | 'import'",
);

const isCustomGroupItemConfiguration = type({
	"+": "reject",
	"elementNamePattern?": isReadonlyArrayOfStrings,
	"groupName?": isString,
	"modifiers?": isImportModifierConfiguration.array().readonly(),
	"selector?": isImportSelectorConfiguration,
}).readonly();

const isLineWrappingStyleConfiguration = type("'greedy' | 'balance'");
const isJsdocConfiguration = type({
	"[string]": isUnknown,
	"addDefaultToDescription?": isBoolean,
	"bracketSpacing?": isBoolean,
	"capitalizeDescriptions?": isBoolean,
	"commentLineStrategy?": isCommentLineStrategyConfiguration,
	"descriptionTag?": isBoolean,
	"descriptionWithDot?": isBoolean,
	"keepUnparsableExampleIndent?": isBoolean,
	"lineWrappingStyle?": isLineWrappingStyleConfiguration,
	"preferCodeFences?": isBoolean,
	"separateReturnsFromParam?": isBoolean,
	"separateTagGroups?": isBoolean,
}).readonly();

const isJsdocUserConfiguration = isBoolean.or(isJsdocConfiguration);
const isNewlinesBetweenMarker = type({
	newlinesBetween: isBoolean,
}).readonly();

const isObjectWrapConfiguration = type("'preserve' | 'collapse'");
const isOperatorPositionConfiguration = type("'start' | 'end'");
const isProseWrapConfiguration = type("'always' | 'never' | 'preserve'");
const isQuotePropertiesConfiguration = type("'as-needed' | 'consistent' | 'preserve'");
const isSortGroupItemConfiguration = isString.or(isReadonlyArrayOfStrings).or(isNewlinesBetweenMarker);
const isSortOrderConfiguration = type("'asc' | 'desc'");

const isSortImportsConfiguration = type({
	"+": "reject",
	"customGroups?": isCustomGroupItemConfiguration.array().readonly(),
	"groups?": isSortGroupItemConfiguration.array().readonly(),
	"ignoreCase?": isBoolean,
	"internalPattern?": isReadonlyArrayOfStrings,
	"newlinesBetween?": isBoolean,
	"order?": isSortOrderConfiguration,
	"partitionByComment?": isBoolean,
	"partitionByNewline?": isBoolean,
	"sortSideEffects?": isBoolean,
}).readonly();

const isSortImportsUserConfiguration = isBoolean.or(isSortImportsConfiguration);
const isSortPackageJsonConfiguration = type({
	"+": "reject",
	"sortScripts?": isBoolean,
}).readonly();

const isSortPackageJsonUserConfiguration = isBoolean.or(isSortPackageJsonConfiguration);
const isSortTailwindcssConfiguration = type({
	"+": "reject",
	"attributes?": isReadonlyArrayOfStrings,
	"Configuration?": isString,
	"functions?": isReadonlyArrayOfStrings,
	"preserveDuplicates?": isBoolean,
	"preserveWhitespace?": isBoolean,
	"stylesheet?": isString,
}).readonly();

const isSortTailwindcssUserConfiguration = isBoolean.or(isSortTailwindcssConfiguration);
const isSvelteConfiguration = type({
	"+": "reject",
	"allowShorthand?": isBoolean,
	"indentScriptAndStyle?": isBoolean,
	"sortOrder?": isString,
}).readonly();

const isSvelteUserConfiguration = isBoolean.or(isSvelteConfiguration);
const isTrailingCommaConfiguration = type("'all' | 'es5' | 'none'");
const isFormatConfiguration = type({
	"+": "reject",
	"arrowParens?": isArrowParensConfiguration,
	"bracketSameLine?": isBoolean,
	"bracketSpacing?": isBoolean,
	"embeddedLanguageFormatting?": isEmbeddedLanguageFormattingConfiguration,
	"endOfLine?": isEndOfLineConfiguration,
	"experimentalOperatorPosition?": isOperatorPositionConfiguration,
	"htmlWhitespaceSensitivity?": isHtmlWhitespaceSensitivityConfiguration,
	"insertFinalNewline?": isBoolean,
	"jsdoc?": isJsdocUserConfiguration,
	"jsxSingleQuote?": isBoolean,
	"objectWrap?": isObjectWrapConfiguration,
	"printWidth?": isInteger,
	"proseWrap?": isProseWrapConfiguration,
	"quoteProps?": isQuotePropertiesConfiguration,
	"semi?": isBoolean,
	"singleAttributePerLine?": isBoolean,
	"singleQuote?": isBoolean,
	"sortImports?": isSortImportsUserConfiguration,
	"sortPackageJson?": isSortPackageJsonUserConfiguration,
	"sortTailwindcss?": isSortTailwindcssUserConfiguration,
	"svelte?": isSvelteUserConfiguration,
	"tabWidth?": isInteger,
	"trailingComma?": isTrailingCommaConfiguration,
	"useTabs?": isBoolean,
	"vueIndentScriptAndStyle?": isBoolean,
}).readonly();

const isOxfmtOverrideConfiguration = type({
	"+": "reject",
	"excludeFiles?": isReadonlyArrayOfStrings,
	files: isReadonlyArrayOfStrings,
	"options?": isFormatConfiguration,
}).readonly();

export const isOxfmtConfiguration = type({
	"+": "delete",
	"arrowParens?": isArrowParensConfiguration,
	"bracketSameLine?": isBoolean,
	"bracketSpacing?": isBoolean,
	"embeddedLanguageFormatting?": isEmbeddedLanguageFormattingConfiguration,
	"endOfLine?": isEndOfLineConfiguration,
	"experimentalOperatorPosition?": isOperatorPositionConfiguration,
	"htmlWhitespaceSensitivity?": isHtmlWhitespaceSensitivityConfiguration,
	"ignorePatterns?": isReadonlyArrayOfStrings,
	"insertFinalNewline?": isBoolean,
	"jsdoc?": isJsdocUserConfiguration,
	"jsxSingleQuote?": isBoolean,
	"objectWrap?": isObjectWrapConfiguration,
	"overrides?": isOxfmtOverrideConfiguration.array().readonly(),
	"printWidth?": isInteger,
	"proseWrap?": isProseWrapConfiguration,
	"quoteProps?": isQuotePropertiesConfiguration,
	"semi?": isBoolean,
	"singleAttributePerLine?": isBoolean,
	"singleQuote?": isBoolean,
	"sortImports?": isSortImportsUserConfiguration,
	"sortPackageJson?": isSortPackageJsonUserConfiguration,
	"sortTailwindcss?": isSortTailwindcssUserConfiguration,
	"svelte?": isSvelteUserConfiguration,
	"tabWidth?": isInteger,
	"trailingComma?": isTrailingCommaConfiguration,
	"useTabs?": isBoolean,
	"vueIndentScriptAndStyle?": isBoolean,
}).readonly();
